language: php

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - composer self-update
  - composer install

before_script:

  - pear channel-discover pear.phpunit.de
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:

  - phpunit ./tests
  - phpcs src
